### ISSUE TITLE
`XMLHTTPException: Not Found (404)` encountered while following example from "Querying US Government Data Sets With Pharo and XMLParser"

### ISSUE THREAD

**Issue by capsulecorplab** [pharo-contributions/XML-XMLParser#12] opened 2022-10-01 21:59 UTC
Example from [Querying US Government Data Sets With Pharo and XMLParser](https://montyos.wordpress.com/2018/04/22/querying-us-government-data-sets-with-pharo-and-xmlparser/) seems to be yielding a 404 error

![Screenshot from 2022-10-01 15-52-42](https://user-images.githubusercontent.com/14095576/193429859-d55eab53-eaca-4575-bdd4-4353f954b367.png)

**Comment by Ducasse** [comment] 2022-10-02 07:32
Tx.
Can you let us know the URL because it looks dead?

**Comment by capsulecorplab** [comment] 2022-10-02 08:01
The exception gets thrown when I try to send the message 
`XMLDOMParser parseURL: 'https://data.medicare.gov/api/views/ypbt-wvdk/rows.xml?accessType=DOWNLOAD'.`

**Comment by capsulecorplab** [comment] 2022-10-02 08:01
I'm not sure where to find the new working URL

**Comment by astares** [comment] 2022-10-04 10:37
This comes from HTTP ERROR 404 as the resource is not found.

Unfortunately even Internet archive does not have a copy of it:  https://web.archive.org/web/20220000000000*/https://data.medicare.gov/api/views/ypbt-wvdk/rows.xml

**Comment by astares** [comment] 2022-10-04 10:42
I was also not able to find it on https://data.cms.gov/provider-data/topics/medicare-plan-finder
(which is a redirect of https://plan-finder.data.medicare.gov)

**Comment by astares** [comment] 2023-03-26 19:53
Anyone still having this data set?

**Comment by astares** [comment] 2023-10-24 09:24
We have no influence on the blog entry or where the data set lives and if it is reachable. 
So this is not a bug of the XML framework itself. 

We will close the issue.

**Closed by astares** 2023-10-24 09:24 UTC
