### ISSUE TITLE
File Reading and writing unsupported in Pharo 9 - 10 - 11

### ISSUE THREAD

**Issue by alesshosry** [pharo-contributions/XML-XMLParser#10] opened 2022-09-09 09:18 UTC
1. For **file writing unsupported**:

- I was running some tests under `XMLFileHandleTest` class, however, as per the first screenshot, all tests that support creating files failed. 
- Screenshot:
![Screenshot 2022-09-09 at 11 05 27 AM](https://user-images.githubusercontent.com/26387399/189316421-081ea21d-1164-4607-b8c1-57325800e798.png)

2. For **file Reading unsupported**:

- I was trying in the playground to parse an existing file under documents/TestFiles folder, but with no success. 
- I tried to change the location of the file (moved it to downloads), also same exception was raised
- I tried `parseFileNamed:`, also I got the same error.
- Screenshot:
![Screenshot 2022-09-09 at 11 08 54 AM](https://user-images.githubusercontent.com/26387399/189316501-a7406545-2eb8-4e4e-a8f5-4178a0ed96f7.png)

**Comment by alesshosry** [comment] 2022-09-09 09:20
I am using:

- Moose 10 image
- Mac machine

**Comment by astares** [comment] 2023-10-24 09:21
@alesshosry 

Looks like a Moose problem as tests are green and working for P9, P10, P11 using the latest code.

![image](https://github.com/pharo-contributions/XML-XMLParser/assets/5980033/08a0569b-7ac9-4af8-b360-2f43fa0946f5)

I willl close the issue here.

**Comment by astares** [comment] 2023-10-26 00:08
Tests are green - but basically because they are skipped. When run manually XMLFileHandleTest and friends they are red.

![image](https://github.com/pharo-contributions/XML-XMLParser/assets/5980033/d79ccc7a-ccf0-4d12-add7-8102917dcbba)

**Comment by astares** [comment] 2023-10-26 00:10
Reason is that 

```Smalltalk
XMLFileWriteStreamFactory findSupportedImplementation
```
![image](https://github.com/pharo-contributions/XML-XMLParser/assets/5980033/e920d4bc-7257-4569-a675-c00c97da7b76)

does not reveal a supported implementation

**Comment by astares** [comment] 2024-05-28 20:29
Actually the mechanism seems to be to provide proper factories.

**Closed** 2024-05-28 20:30 UTC

**Comment by astares** [comment] 2024-05-28 20:32
The commit https://github.com/pharo-contributions/XML-XMLParser/commit/02fa5ed7cc720af09f0930a3670be60a17979141 moves that forward. 

But you still get an error as the problem is that not all zinc buffers understand #reset yet in Pharo 10 / 11 / 12 / 13. 

But this we must solve in standard image
